/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MovimentacaoRouteImport } from './routes/movimentacao'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacaoRoute = MovimentacaoRouteImport.update({
  id: '/movimentacao',
  path: '/movimentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/config': typeof ConfigRoute
  '/movimentacao': typeof MovimentacaoRoute
  '/produtos': typeof ProdutosRoute
  '/promocoes': typeof PromocoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/config': typeof ConfigRoute
  '/movimentacao': typeof MovimentacaoRoute
  '/produtos': typeof ProdutosRoute
  '/promocoes': typeof PromocoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/config': typeof ConfigRoute
  '/movimentacao': typeof MovimentacaoRoute
  '/produtos': typeof ProdutosRoute
  '/promocoes': typeof PromocoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/clientes'
    | '/compras'
    | '/config'
    | '/movimentacao'
    | '/produtos'
    | '/promocoes'
    | '/relatorios'
    | '/servicos'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/clientes'
    | '/compras'
    | '/config'
    | '/movimentacao'
    | '/produtos'
    | '/promocoes'
    | '/relatorios'
    | '/servicos'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/clientes'
    | '/compras'
    | '/config'
    | '/movimentacao'
    | '/produtos'
    | '/promocoes'
    | '/relatorios'
    | '/servicos'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  ConfigRoute: typeof ConfigRoute
  MovimentacaoRoute: typeof MovimentacaoRoute
  ProdutosRoute: typeof ProdutosRoute
  PromocoesRoute: typeof PromocoesRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ServicosRoute: typeof ServicosRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacao': {
      id: '/movimentacao'
      path: '/movimentacao'
      fullPath: '/movimentacao'
      preLoaderRoute: typeof MovimentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  ConfigRoute: ConfigRoute,
  MovimentacaoRoute: MovimentacaoRoute,
  ProdutosRoute: ProdutosRoute,
  PromocoesRoute: PromocoesRoute,
  RelatoriosRoute: RelatoriosRoute,
  ServicosRoute: ServicosRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
